selectors:
  friend: 'div[data-pnref="all"]'
  mutual_friend: 'div[data-pnref="mutual"]'
  # section next to friends section
  next_section:
    - '#pagelet_timeline_medley_music'
    - '#pagelet_timeline_medley_books' 
    - '#pagelet_timeline_medley_photos'
    - '#pagelet_timeline_medley_videos'

  img_link: 'a'
  deactivated: 'a > img'

num_pages: -1

friends:
  # get friends
  get: true
  # get mutual friends
  get_mutual: true
  # get friend's friends
  get_friends: false
  # save friends
  save: true
  # download friends profile thumbnails
  download_thumb: true

photos:
  path: 'friends_photos'